---
- name: ensure dnsmasq is installed
  package:
    name: "dnsmasq"
    state: present

- name: configure dnsmasq
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart dnsmasq

- meta: flush_handlers

- name: ensure dnsmasq is started and enabled
  service:
    name: "dnsmasq"
    state: started
    enabled: true
